# Generated by Django 2.1.5 on 2019-08-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(blank=True)),
                ('comments', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
