# Generated by Django 2.1.5 on 2019-08-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_conversion_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='conversion_rate',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
