# Generated by Django 2.1.5 on 2019-08-04 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190804_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='servicing', to='shop.Product'),
        ),
    ]
