# Generated by Django 2.1.5 on 2019-08-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190805_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='support',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
