# Generated by Django 2.1.5 on 2019-08-06 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_services_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='services_available',
        ),
    ]
